# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/ashkitten/mastodon.git";
    rev = "a2e881a621f136d33cbcf72a04def9e9b4f5a5e7";
    sha256 = "1mc4b3a5rvp82pqgbk51bz8578zf5bbq2bpc0ackfyspzm46fck1";
  };
in applyPatches {
  inherit src;
  patches = [ ./version.patch ];
}
