# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/ashkitten/mastodon.git";
    rev = "283d06ee5bbbdeb5569d1d328a2578c59070b24c";
    sha256 = "1ll76fl4ism2fmaqx3x599lxhfw5an8q8adzxx2hyqxng0sj5gkk";
  };
in applyPatches {
  inherit src;
  patches = [ ./version.patch ];
}
