# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/ashkitten/mastodon";
    rev = "1abb0534140bc9fc12dbf7fd10d198c712b11e06";
    sha256 = "0mi5b53cf5w92cwybg54ns88jnyhcxvaqjha2abgx2s07ficr2n4";
  };
in applyPatches {
  inherit src;
  patches = [ ./version.patch ];
}
