colorscheme tomorrow-night

add-highlighter global/ number-lines

# important
set-option global ui_options ncurses_assistant=cat

map global normal <a-tab> ': nop %sh{ kitty @ launch --location=first ranger --cmd="set viewmode=multipane" }<ret>' -docstring 'open ranger file browser pane'

map global user y '<a-|>wl-copy<ret>' -docstring 'copy to the system clipboard'
map global user p '!wl-paste<ret>' -docstring 'paste from the system clipboard'

## lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

map global user l ': enter-user-mode lsp<ret>' -docstring 'enter user lsp mode'
map global lsp  n ': lsp-find-error --include-warnings<ret>' -docstring 'find next warning or error'
map global lsp  l ': lsp-enable-window<ret>' -docstring 'enable lsp for this window'
map global lsp  r ': lsp-rename-prompt<ret>' -docstring 'rename symbol under cursor'

## backup selections
hook -group backup-selections global NormalIdle .* %{
  set-register b %reg{z}
  execute-keys -draft '"zZ'
}
map global user z '"bz' -docstring 'restore selections from the [b]ackup register'

powerline-start

## smarttab
require-module smarttab

## sleuth
require-module sleuth

hook -group sleuth global BufOpenFile .* %{
  expandtab
  sleuth
  set-option buffer softtabstop %opt{indentwidth}
}

hook -group sleuth global BufWritePost .* %{
  sleuth
  set-option buffer softtabstop %opt{indentwidth}
}

map global normal x <a-x>
map global normal X giGl
map global normal <a-x> ghGl
